#+TITLE: Emacs Configuration
#+OPTIONS: toc:nil
#+STARTUP: showall

* Offene Punkte

** Diminish doesn't work

Should be in after-init-hook?

* Before everything else

** Terminal-Specific Stuff

Scrolling did not work out of the box, when using emacs inside tmux,
but the frame receives mouse events, so bind the correct commands
manually.

TODO Scroll Amount seems to be a bit much, can we customize that?

#+BEGIN_SRC emacs-lisp
  (unless (display-graphic-p)
    (defmacro cla/window-frac (frac) `(/ (window-total-height) ,frac))
    (global-set-key (kbd "<mouse-4>") (lambda ()
                                        (interactive)
                                        (scroll-down-command (cla/window-frac 10))))
    (global-set-key (kbd "<mouse-5>") (lambda ()
                                        (interactive)
                                        (scroll-up-command (cla/window-frac 10))))
    (global-set-key (kbd "<prior>") (lambda ()
                                      (interactive)
                                      (scroll-down-command (cla/window-frac 2))))
    (global-set-key (kbd "<next>") (lambda ()
                                     (interactive)
                                     (scroll-up-command (cla/window-frac 2)))))
#+END_SRC

Hack for running emacs in Windows Terminal + SSH to Linux
Box. Ctrl+Space doesn't work for set-mark command so we send a weird
combo.

#+BEGIN_SRC js
{
  "command": {
    "action": "sendInput",
    "input": "\u001b[9~"
  },
  "keys": "ctrl+space"
}
#+END_SRC

Insert the above command in Windows Terminal, and the below binding
will do the trick:

#+BEGIN_SRC emacs-lisp
(global-set-key "\e[9~" 'set-mark-command)
#+END_SRC

# C-<f1> to C-<f4> seem to not work smh, resolve this.

# #+BEGIN_SRC emacs-lisp
# (global-set-key (kbd "\e[1;5r")
#                 (lambda () (interactive) (funcall (global-key-binding (kbd "C-<f3>")))))
# (global-set-key (kbd "\e[1;5S")
#                 (lambda () (interactive) (funcall (global-key-binding (kbd "C-<f4>")))))
# #+END_SRC

Next enable emacs to kill to tmux clipboard,
TODO this ideally should have a check, wether
     this is running in tmux context i guess.

#+BEGIN_SRC emacs-lisp
(defun cla/kill-to-tmux (s)
  (let ((tmux (executable-find "tmux")))
    (if tmux
      (call-process "/usr/bin/tmux" nil nil nil "set-buffer" "-w" s))))

(defun cla/gui-select-text (s)
  (cla/kill-to-tmux s)
  (gui-select-text s))

(setq interprogram-cut-function 'cla/gui-select-text)
#+END_SRC

** Clean UI

Initial Frame size is a bit small for modern screens

#+BEGIN_SRC emacs-lisp
  (setq default-frame-alist
    '((width . 120)
      (height . 50)))
#+END_SRC

Remove all those noobish frame decorations. First two are only
available when running on a graphical display.

#+BEGIN_SRC emacs-lisp
  (ignore-errors
    (tool-bar-mode -1)
    (scroll-bar-mode -1))
  (menu-bar-mode 0)
  (setq inhibit-startup-screen t)
  (global-hl-line-mode 1)
  (xterm-mouse-mode)
#+END_SRC

On TTYs we want a nice vertical border:

#+BEGIN_SRC emacs-lisp
(let ((display-table (or standard-display-table (make-display-table))))
  (set-display-table-slot display-table 'truncation (make-glyph-code ?→))
  (set-display-table-slot display-table 'vertical-border (make-glyph-code ?│))
  (set-display-table-slot display-table 'wrap (make-glyph-code ?↲))
  (setq standard-display-table display-table))
#+END_SRC

** Theme Setup I

#+BEGIN_SRC emacs-lisp
  (defconst cla/the-theme-pkg
    'dracula-theme)
  (defconst cla/the-theme
    'dracula)
#+END_SRC

... let's load up our theme if it exists. Otherwise
we would have to wait for package initialization to
complete while staring at a white window -.-

#+BEGIN_SRC emacs-lisp
  (ignore-errors
    (require 'package)
    (package-initialize)
    (load-theme cla/the-theme))
#+END_SRC

However if we don't have it installed yet, we try a
second time, after package initialization.

** Font Setup

#+BEGIN_SRC emacs-lisp
  (defvar cla/font-family "SauceCodePro NF")
  (defvar cla/font-height-default 110)
  (set-face-attribute 'default nil
                      :family cla/font-family :height cla/font-height-default)
#+END_SRC

* Setup package.el + use-package

#+BEGIN_SRC emacs-lisp
  (add-to-list 'package-archives
    '("melpa" . "http://melpa.org/packages/") t)
  (package-refresh-contents)

  (defun cla/install-from-elpa (package)
    (unless (package-installed-p package)
      (package-install package)))

  (cla/install-from-elpa 'use-package)
#+END_SRC

* General setup

** Daemon Setup

#+BEGIN_SRC emacs-lisp
(use-package exec-path-from-shell
  :ensure t
  :config
  (when (daemonp)
    (exec-path-from-shell-initialize)))
#+END_SRC

** Theme Setup II

#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p cla/the-theme-pkg)
    (package-install cla/the-theme-pkg)
    (load-theme cla/the-theme))
#+END_SRC

** Sane Code Formatting

#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil) ; never insert tabs
  (setq-default tab-width 4)          ; always indent 4 spaces
  (setq-default c-basic-offset 4)     ; c-mode indent 4 spaces
  (add-hook 'before-save-hook         ; on save remove trailing whitespace
            'delete-trailing-whitespace)
  (set-language-environment "UTF-8")
  (setq-default buffer-file-coding-system 'utf-8-unix)
#+END_SRC

** Visual Bell

#+BEGIN_SRC emacs-lisp
  (setq visible-bell nil
        ring-bell-function 'flash-mode-line)
  (defun flash-mode-line ()
    (invert-face 'mode-line)
    (run-with-timer 0.1 nil #'invert-face 'mode-line))
#+END_SRC

** Clean Directories

Disable emacs to auto-create files when editing

#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil) ; stop creating backup~ files
  (setq auto-save-default nil) ; stop creating #autosave# files
#+END_SRC

** Keychords

windmove is bound to meta, so we can move between adjacent
windows using Alt+Arrow Keys, instead of C-x o. Note that this
collides with default org-mode keys, so first unbind those.

#+BEGIN_SRC emacs-lisp
  (define-key org-mode-map (kbd "<M-up>") nil)
  (define-key org-mode-map (kbd "<M-down>") nil)
  (define-key org-mode-map (kbd "<M-left>") nil)
  (define-key org-mode-map (kbd "<M-right>") nil)
#+END_SRC

tmux-windmove provides replacements for windmove-* functions.
When there is no window in the direction we're moving this will
use tmux select-pane to select the next pane in that direction.

#+BEGIN_SRC emacs-lisp
  (require 'tmux-windmove)
  (tmux/windmove-meta-binding)
#+END_SRC

In order to really work the corresponding part is found in dotfiles:
This contains tmux-configuration to redirect M-<arrow> events to
emacs, if the current pane is running in emacs.

The other key bindings resize the current window using
the arrow keys and Shift+Alt. Useful if you need to see more.

#+BEGIN_SRC
  (global-set-key (kbd "S-M-<up>") 'enlarge-window)
  (global-set-key (kbd "S-M-<down>") 'shrink-window)
  (global-set-key (kbd "S-M-<left>") 'shrink-window-horizontally)
  (global-set-key (kbd "S-M-<right>") 'enlarge-window-horizontally)
#+END_SRC

cla/switch-to-other-buffer is useful when editing two files
in one buffer, for example source/header file.

#+BEGIN_SRC emacs-lisp
  (defun cla/switch-to-other-buffer ()
    (interactive)
    (switch-to-buffer (other-buffer (current-buffer))))

  (global-set-key (kbd "C-<tab>") 'cla/switch-to-other-buffer)
#+END_SRC

This makes home/C-a navigate back to indentation or if
already at indentation col 0, which is more in line with modern
editors.

#+BEGIN_SRC emacs-lisp
  (defun cla/back-to-indentation-or-beginning ()
    (interactive)
    (if (= (point) (progn (back-to-indentation) (point)))
        (beginning-of-line)))

  (global-set-key (kbd "C-a") 'cla/back-to-indentation-or-beginning)
  (global-set-key (kbd "<home>") 'cla/back-to-indentation-or-beginning)
#+END_SRC

*** Error Navigation

next-error/previous-error allow navigating matches e.g. generated from
grepping. These bindings are comfortably reached with the right hand
when using an ansi layout:

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-<prior>") 'previous-error)
(global-set-key (kbd "C-<next>") 'next-error)
#+END_SRC

Note: the escape code of "M-[" is the prefix of many Meta-Escape
Codes, e.g. "M-ArrowKeys" and xterm mouse mode.
Disabling this, so we can use all these inputs on terminal.
TODO how can we en-/disable these based on frame?
Global minor mode that is toggled when we switch frames?

** Search

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-<f3>") 'rg-dwim-project-dir)
  (global-set-key (kbd "C-S-<f3>") 'rg-project)
#+END_SRC

** Dired

This enables the 'a' key in dired, which can be used to open the
file or directory at point in the same buffer.

#+BEGIN_SRC emacs-lisp
(put 'dired-find-alternate-file 'disabled nil)
#+END_SRC

* Packages

Let's ensure diminish is installed so we can use it later on.

#+BEGIN_SRC emacs-lisp
  (use-package diminish
    :ensure t)
#+END_SRC

** Random Stuff

Stuff that doesn't need much setup

#+BEGIN_SRC emacs-lisp
  (use-package rg
    :ensure t)
  (use-package htmlize
    :ensure t)
  (use-package markdown-mode
    :ensure t
    :bind (("C-c i c" . markdown-insert-change-request)
           ("C-c i p" . markdown-insert-person)))
#+END_SRC

** Magit

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t)
#+END_SRC

Function to open magit-status in the selected window. Use in
combination with emacsclient -c to open magit-status from shell.

#+BEGIN_SRC emacs-lisp
  (defun cla/magit-status-same-window ()
    (let ((magit-display-buffer-function (lambda (buffer)
                                           (display-buffer buffer '(display-buffer-same-window)))))
      (magit-status)))
#+END_SRC

** Global Utilies

*** Diff HL Mode

Highlight modified lines of code in files under version control

#+BEGIN_SRC emacs-lisp
(use-package diff-hl
  :ensure t
  :defer 2
  :config
  (global-diff-hl-mode)
  (diff-hl-margin-mode))
#+END_SRC

*** Smart Parens

#+BEGIN_SRC emacs-lisp
  (use-package 'smartparens
    :ensure t
    :diminish smartparens-mode
    :config (progn
              (require 'smartparens-config)
              (smartparens-global-mode)
              (show-smartparens-global-mode)
              (global-set-key (kbd "C-.") 'sp-select-next-thing)))
#+END_SRC

*** Company Mode

Basic Company Setup

#+BEGIN_SRC emacs-lisp
  (cla/install-from-elpa 'company)
  (setq company-dabbrev-downcase nil)
  (setq company-minimum-prefix-length 2)
  (setq company-idle-delay 0)
  (add-hook 'after-init-hook 'global-company-mode)
  (with-eval-after-load 'company
    (diminish 'company-mode))
#+END_SRC

Company Box is a company frontend that supports icons

#+BEGIN_SRC emacs-lisp
(use-package company-box
  :ensure t
  :config
  (diminish 'company-box-mode)
  :hook
  (company-mode . company-box-mode))
#+END_SRC

*** Projectile

#+BEGIN_SRC emacs-lisp
  (defconst cla/projectile-svn-command
    "fd -0 --exclude linux2-x64 . $(svn info --show-item wc-root)")

  (cla/install-from-elpa 'projectile)
  (projectile-global-mode)
  (setq projectile-mode-line-prefix " ")
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (if (executable-find "fd")
    (setq projectile-svn-command cla/projectile-svn-command))
#+END_SRC

#+BEGIN_SRC
  (global-set-key (kbd "C-c p f") 'projectile-find-file)
  (global-set-key (kbd "C-c p g") 'projectile-grep)
  (global-set-key (kbd "C-c p s") 'projectile-switch-project)
  (global-set-key (kbd "C-c p k") 'projectile-kill-buffers)
  (global-set-key (kbd "<f9>") 'projectile-switch-project)
  (global-set-key (kbd "<f10>") 'projectile-find-file)
#+END_SRC

Let's enable native indexing/no caching, if the system has git and fd
this should be sufficiently efficient:

#+BEGIN_SRC emacs-lisp
  (setq projectile-indexing-method 'alien)
  (setq projectile-enable-caching nil)
#+END_SRC

*** Helm

#+BEGIN_SRC emacs-lisp
  (cla/install-from-elpa 'helm)
  ; (require 'helm-config)
  (require 'helm)
  (helm-mode 1)
#+END_SRC

We want our Helm Buffer to always open in the bottom part of the
window we're in. This makes it rather predictable.

#+BEGIN_SRC emacs-lisp
  (setq helm-split-window-in-side-p t)
  (setq helm-split-window-default-side 'below)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (with-eval-after-load "helm"
    (global-set-key (kbd "C-x C-f") #'helm-find-files)
    (global-set-key (kbd "M-x") #'helm-M-x)
    (define-key helm-find-files-map "\t" 'helm-execute-persistent-action)
    (define-key helm-read-file-map "\t" 'helm-execute-persistent-action)
    (diminish 'helm-mode))
#+END_SRC

Finally we need Helm to interact with projectile

#+BEGIN_SRC emacs-lisp
(use-package helm-projectile
  :ensure t
  :config
  (helm-projectile-on))
#+END_SRC

*** Smart Mode Line

#+BEGIN_SRC emacs-lisp
  (cla/install-from-elpa 'smart-mode-line)
  (setq sml/theme 'dark)
  (sml/setup)
#+END_SRC

*** COMMENT Flycheck

#+BEGIN_SRC emacs-lisp
  ;; (cla/install-from-elpa 'flycheck)
  ;; (use-package flycheck
  ;;   :ensure t
  ;;   :init (global-flycheck-mode))
  ;; (setq flycheck-check-syntax-automatically '(mode-enabled save))
  ;; (setq-default flycheck-disabled-checkers '(c/c++-gcc c/c++-clang javascript-jshint))
  ;; (add-hook 'after-init-hook #'global-flycheck-mode)
  ;; (flycheck-add-mode 'javascript-eslint 'rjsx-mode)
#+END_SRC

* CEDM

** Working with Change Requests

#+BEGIN_SRC
(defconst cla/markdown-insert-cr-command
  "ceget cdberror %s | jq -r '.[] | [.[\"system:description\"], .[\"system:ui_link\"]] | \"[\\(.[0])](\\(.[1]))\"'")

(defun markdown-insert-change-request (cr)
  (interactive
   (list (read-string "Change Request ID: ")))
  (if (not (string-match-p "^E[0-9]\\{6\\}$" cr))
      (error "'%s' is no valid Change Reques  ID."))
  (insert
   (string-trim-right
    (shell-command-to-string
     (format cla/markdown-insert-cr-command cr)))))

(defconst cla/markdown-insert-person-command
  "ceget person %s | jq -r '.[0][\"system:description\"]'")

(defun markdown-insert-person (person)
  (interactive
   (list (read-string "Person ID: ")))
  (insert
   (string-trim-right
    (shell-command-to-string
     (format cla/markdown-insert-person-command person)))))
#+END_SRC

* Web Development

Some minor major-modes (lol) for common formats

#+BEGIN_SRC emacs-lisp
  (cla/install-from-elpa 'yaml-mode)
  (cla/install-from-elpa 'mustache-mode)
  (require 'mustache-mode)
#+END_SRC

I think for Javascript/JSX based types I should replace this RJSX.

#+BEGIN_SRC emacs-lisp
  (cla/install-from-elpa 'web-mode)
  (cla/install-from-elpa 'rjsx-mode)

  (dolist (suffix '("\\.js\\'" "\\.jsx\\'"))
    (add-to-list 'auto-mode-alist `(,suffix . rjsx-mode)))

  (dolist (suffix '("\\.tsx\\'" "\\.ts\\'" "\\.json\\'" "\\.html\\'" "\\.css\\'"))
    (add-to-list 'auto-mode-alist `(,suffix . web-mode)))

  (dolist (suffix '("\\.scss\\'"))
    (add-to-list 'auto-mode-alist `(,suffix . scss-mode)))
#+END_SRC

Customize indentation

#+BEGIN_SRC emacs-lisp
  (setq sgml-basic-offset 4)
#+END_SRC

TODO I should check RJSX for Typescript.
